language: python

sudo: false

python:
  - "2.7"


before_install:
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  py.test -v --cov==dk .

after_success:
  coveralls
